Transform: AWS::Serverless-2016-10-31
Description: Spot Drainer - drain spot ECS instances before interruption

Resources:
  spotDrainer:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: spot-drainer
      Description: "remember to drain your spot fleet"
      Handler: main
      Runtime: go1.x
      Timeout: 20
      Policies:
        - Statement:
          - Effect: "Allow"
            Action:
              - "ecs:DescribeContainerInstances"
              - "ecs:ListClusters"
              - "ecs:ListContainerInstances"
              - "ecs:UpdateContainerInstancesState"
            Resource: "*"
      CodeUri: ./source/handler.zip
      Events:
        SpotInterruptionWarning:
          Type: CloudWatchEvent
          Properties:
            Pattern:
              source: ["aws.ec2"]
              detail-type: ["EC2 Spot Instance Interruption Warning"]

# eof
